### ISSUE TITLE
could't find config.properties file

### ISSUE THREAD

**Issue by jose2007kj** [sighmon/NewInternationalist#2]
sir,
I would like to view the config.properties file.
If its a confidential file then would you please provide me a similar file such that it wont cause you security problems...............I am trying to developing an magazine app as a part of my job training 
Anyway this open source project is helping me a lot as a beginner ......may god bless you............
thanks in advance

**Comment by sighmon** [comment]
Sure thing.
It should look something like this:

``` properties
# app/src/main/assets/config.properties

PUBLIC_KEY=xxx
EMAIL_ADDRESS=xxx
PARSE_APP_ID=xxx
PARSE_CLIENT_KEY=xxx
GOOGLE_ANALYTICS=xxx
GOOGLE_ANALYTICS_DEV=xxx
ADWORDS_ID=xxx
ADWORDS_KEY=xxx
SITE_URL=https://www.yoursite.com
```

**Comment by jose2007kj** [comment]
Thanks a lot............god bless you
